spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userinfo?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 9821
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
redis:
  host: localhost
  port: 6379

